name: ci

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Tests
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Save build artifacts
        uses: actions/cache/save@v4
        with:
          path: ./build
          key: ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}

  release:
    needs: [build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'

      - name: Set up Git
        run: |
          git config --global user.name 'Artem Zakharchenko'
          git config --global user.email 'kettanaito@gmail.com'

      - name: Install dependencies
        run: pnpm install

      - name: Restore build artifacts
        uses: actions/cache/restore@v4
        with:
          path: ./build
          key: ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Release
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
